name: Docker Image CI

on:
  push:
    tags:
      - 'v*' 
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/spring-demo:${{ github.ref_name }}
      DOCKER_LATEST: ${{ secrets.DOCKERHUB_USERNAME }}/spring-demo:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests
      
      - name: Build the Docker image
        run: docker build --file Dockerfile -t $DOCKER_IMAGE -t $DOCKER_LATEST .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        run: 
          docker push $DOCKER_IMAGE
          docker push $DOCKER_LATEST
